FROM ubuntu:22.04

# update the repository sources list and install necessary dependencies
RUN apt update && apt upgrade -y

#Install Initial Packages for PHP PPA on Ubuntu
RUN apt install -y ca-certificates apt-transport-https software-properties-common \
    lsb-release wget curl zip unzip git

#Add PHP PPA Repository
RUN add-apt-repository ppa:ondrej/php -y

#Update & Upgrade apt packages
RUN apt update && apt upgrade -y

#Install PHP as an Apache Module
RUN DEBIAN_FRONTEND=noninteractive apt install php8.2 libapache2-mod-php8.2 -y 

#Restart Apache Web Server
RUN service apache2 restart

#change the working directory to /var/www/html
WORKDIR /var/www/html


RUN apt-get update && apt-get install -y \
        unzip \
        libfreetype6-dev \
        libaio1 \
        libmcrypt-dev \
        php8.2-mysql \
        php8.2-mbstring \
        php8.2-xml \
        php8.2-zip \
        php8.2-gd \
        php8.2-curl \
        php8.2-mbstring \
        php8.2-iconv \
        supervisor


RUN mkdir /opt/oracle
WORKDIR /opt/oracle
RUN curl -L https://download.oracle.com/otn_software/linux/instantclient/1919000/instantclient-basic-linux.arm64-19.19.0.0.0dbru.zip -O
RUN curl -L https://download.oracle.com/otn_software/linux/instantclient/1919000/instantclient-sdk-linux.arm64-19.19.0.0.0dbru.zip -O
# RUN cd /tmp && curl -L https://download.oracle.com/otn_software/linux/instantclient/1919000/instantclient-sqlplus-linux.arm64-19.19.0.0.0dbru.zip -O

RUN unzip "*.zip"
RUN echo /opt/oracle/instantclient_19_19 > /etc/ld.so.conf.d/oci8.conf
RUN ldconfig

#install pecl via pear
RUN apt-get update && apt-get install -y \
        php-pear \
        php8.2-dev \
        gcc \
        make

RUN echo "instantclient,/opt/oracle/instantclient_19_19" | pecl install oci8

# RUN echo 'instantclient,/usr/local/instantclient' | pecl install oci8
RUN echo "extension=oci8" > /etc/php/8.2/apache2/conf.d/20-oci8.ini
RUN echo "extension=oci8" > /etc/php/8.2/cli/conf.d/20-oci8.ini

RUN a2enmod actions alias rewrite proxy proxy_http
RUN phpenmod opcache

# Composer install
RUN curl -sS https://getcomposer.org/installer | php
RUN mv composer.phar /usr/local/bin/composer

# Update the default apache site with the config we created.
ADD config/apache/apache-vhosts.conf /etc/apache2/sites-enabled/000-default.conf
ADD config/apache/apache2.conf /etc/apache2/apache2.conf

# Update php.ini
ADD config/php/php.conf /etc/php/8.2/apache2/php.ini

RUN service apache2 restart

RUN chown -R www-data:www-data /var/www

WORKDIR /var/www/

EXPOSE 80

CMD ["apache2ctl", "-D", "FOREGROUND"]